### ISSUE TITLE
Could one simplify the YAML metadata?

### ISSUE THREAD

**Issue by maelle** [schochastics/cynkrablog#1]
I wonder how

```yaml
filters:
  - cynkrablog
format:
  gfm:
    variant: gfm+yaml_metadata_block
```

could become

```yaml
format: cynkrablog
```

if it is at all possible.
